[package]
name = "rust-bms"
version = "0.1.0"
authors = ["Ico Doornekamp <ico@zevv.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
